name: bexel
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #Package for base app and structure
  flutter_phoenix: ^1.1.1
  get_it: ^8.0.3
  flutter_easyloading: ^3.0.5
  app_links: ^6.4.0
  share_plus: ^11.0.0
  flutter_portal: ^1.1.4
  country_code_picker: ^3.3.0
  pinput: ^5.0.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.2
  #Package for State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  #Package for responsive app and fonts
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.1.1
  flutter_svg: ^2.2.0
  #Package for Languague and localiztion
  easy_localization: ^3.0.7+1
  #Package for Rest pi
  dio: ^5.8.0+1
  http: ^1.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  logger: ^2.5.0
  #Package for caching data locally
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
